spring:
  datasource:
    url: ${TEST_DB_URL:jdbc:postgresql://localhost:5432/safeinvestor}
    username: ${TEST_DB_USERNAME:safeinvestor}
    password: ${TEST_DB_PASSWORD:safeinvestor}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    clean-disabled: false
  thymeleaf:
    cache: false

logging:
  level:
    org.flywaydb: INFO
