spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    clean-disabled: false
  thymeleaf:
    cache: false

logging:
  level:
    org.testcontainers: INFO
    com.github.dockerjava: WARN
